apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: arkid
  namespace: arkid
spec:
  chart: arkid
  version: 3.3.0
  repo: https://harbor.longguikeji.com/chartrepo/public
  targetNamespace: arkid
  valuesContent: |-
    apisix:
      etcd:
        volumePermissions: 
          enabled: true
    redis:
      volumePermissions: 
        enabled: true
    persistence:
      init: true
      storageClass:
      accessMode: ReadWriteMany
      size: 8Gi
    be:
      resources:
        limits: {}
        requests: {"cpu": "100m", "memory": "256Mi"}
    fe:
      resources:
        limits: {}
        requests: {"cpu": "100m", "memory": "256Mi"}
    mysql:
      volumePermissions: 
        enabled: true
      architecture: standalone
      auth:
        rootPassword: root
        database: arkid
        username: arkid
        password: arkid
      primary:
        persistence:
          enabled: true
        resources:
          limits: {}
          requests: {"cpu": "100m", "memory": "256Mi"}
