{{- if false -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkid.name" . }}-hc
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}-hc
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arkid.name" . }}-hc
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
      app.kubernetes.io/name: {{ include "arkid.name" . }}-hc
      app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "arkid.name" . }}-hc
          image: {{ .Values.hc.image }}
          command: ["helm-controller"]
{{- end }}