---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "arkid.fullname" . }}-portal"
  labels:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-portal"
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}-portal"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.portal.svcType }}
  ports:
    - port: 80
      {{ if eq .Values.portal.svcType "NodePort" }}
      nodePort: 32580
      {{ end }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-portal"
    app.kubernetes.io/instance: "{{ .Release.Name }}-portal"
---
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "arkid.fullname" . }}-portal
  labels:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-portal"
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}-portal"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arkid.name" . }}-portal
      app.kubernetes.io/instance: {{ .Release.Name }}-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arkid.name" . }}-portal
        app.kubernetes.io/instance: {{ .Release.Name }}-portal
    spec:
    {{- if or .Values.portal.nodeAffinity .Values.portal.podAffinity .Values.portal.podAntiAffinity }}
      affinity:
      {{- with .Values.portal.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.portal.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- if .Values.portal.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml .Values.portal.podAntiAffinity | nindent 10 }}
      {{- end }}
    {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-portal"
          image: "{{ .Values.portal.image}}"
          imagePullPolicy: {{ .Values.portal.pullPolicy }}
          env:
            - name: TZ
              value: 'Asia/Shanghai'
          volumeMounts:
            - name: settings-local
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "default.conf"
      {{- if .Values.portal.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.portal.nodeSelector | indent 8 }}
      {{- end }}
      volumes:
        - name: settings-local
          configMap:
            name: "{{ template "arkid.fullname" . }}"
