---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "arkid.fullname" . }}-desktop"
  labels:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-desktop"
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}-desktop"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-desktop"
    app.kubernetes.io/instance: "{{ .Release.Name }}-desktop"
---
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "arkid.fullname" . }}-desktop
  labels:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-desktop"
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}-desktop"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arkid.name" . }}-desktop
      app.kubernetes.io/instance: {{ .Release.Name }}-desktop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arkid.name" . }}-desktop
        app.kubernetes.io/instance: {{ .Release.Name }}-desktop
    spec:
      containers:
        - name: "{{ .Chart.Name }}-desktop"
          image: "{{ .Values.desktop.image}}"
          imagePullPolicy: {{ .Values.desktop.pullPolicy }}
          env:
            - name: TZ
              value: 'Asia/Shanghai'
          volumeMounts:
            - name: settings-local
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "desktop.conf"
      {{- if .Values.desktop.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.desktop.nodeSelector | indent 8 }}
      {{- end }}
      volumes:
        - name: settings-local
          configMap:
            name: arkid
