version: '3.5'
services:
  portal:
    image: nginx:alpine
    container_name: ${INSTANCE}-portal
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - arkid
    ports:
      - 8989:80
    depends_on:
      - be
      - fe
    volumes:
      - ${WORKSPACE}/portal.conf:/etc/nginx/conf.d/default.conf
  be:
    image: registry.cn-zhangjiakou.aliyuncs.com/ark-releases/arkid:latest
    container_name: ${INSTANCE}-be
    sysctls:
      - net.core.somaxconn=65535
    restart: always
    command: supervisord
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=${INSTANCE}-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=arkid
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${INSTANCE}-redis
    networks:
      - arkid
    depends_on:
      - db
    volumes:
      - ${WORKSPACE}/settings_local.py:/var/arkid/settings_local.py
      - ${WORKSPACE}/arkid.local.toml:/var/arkid/arkid.local.toml
      - ${WORKSPACE}/supervisord.conf:/var/arkid/supervisord.conf
      - ${WORKSPACE}/be/certificates:/var/arkid/extension_root/saml2/certificates
      - ${WORKSPACE}/be/metadatas:/var/arkid/extension_root/saml2/metadatas
      - ${WORKSPACE}/be/be:/data
      - ${WORKSPACE}/be/arkidextensions:/var/arkid/arkid_extensions
  fe:
    image: ""
    container_name: ${INSTANCE}-fe
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - arkid
    volumes:
      - ${WORKSPACE}/fe.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7
    container_name: ${INSTANCE}-db
    restart: always
    networks:
      - arkid
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=arkid
    volumes:
      - ${WORKSPACE}/db/data:/var/lib/mysql
      - ${WORKSPACE}/db/config:/etc/mysql/conf.d
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  ## 需要ldap功能的话将以下解除注释，需配合ldap插件使用
  # ldap:
  #   image: registry.cn-zhangjiakou.aliyuncs.com/ark-releases/ldapjs:latest
  #   container_name: ${INSTANCE}-ldap
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - BEURL=http://be
  #   networks:
  #     - arkid
  #   depends_on:
  #     - be
  #   ports:
  #     - ${LDAP_PORT}:1389
  #   environment:
  #     - TZ=Asia/Shanghai
  redis:
    image: redis:5.0.3
    container_name: ${INSTANCE}-redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - arkid
  docs:
    image: registry.cn-zhangjiakou.aliyuncs.com/ark-releases/arkid:latest
    container_name: ${INSTANCE}-docs
    sysctls:
      - net.core.somaxconn=65535
    restart: always
    command:
      - mkdocs
      - serve
    environment:
      - TZ=Asia/Shanghai
    networks:
      - arkid
    volumes:
      - ${WORKSPACE}/mkdocs.yml:/var/arkid/mkdocs.yml
networks:
  arkid:
    name: ${INSTANCE}
    driver: bridge
