## STATIC CONFIGURATION
log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  ali:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: xxxx@yyy.zzz
      storage: /etc/acme/acme.json
      dnsChallenge:
        provider: alidns