name: arkidhelmcharts
on:
  workflow_dispatch:
  push:
    branches:
      - v2.5-dev
    paths:
      - 'chart/**'
jobs:
  buildyaml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'
    - run: |
        kubectl get nodes

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.2
    - run: |
        helm list
    - run: |
        ls
    - run: |
        helm install --dry-run -n arkidv2 arkidv2 ./chart \
        --set ingress.enabled=false \
        --set ingress.cert=false \
        --set ingress.tls=false \
        --set ingress.host.name="\{\{hostvars['arkos-master01']['ansible_ssh_host']\}\}\:32580" \
        --set persistence.init=true \
        --set persistence.size=10Gi \
        --set portal.svcType=NodePort \
        --set be.podAntiAffinity.type=soft > arkidv25.yaml
    - run: |
        helm list
    - run: |
        cat arkidv25.yaml