name: Lint and Test Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [latest,v1.21.2-k3s1,v1.20.8-k3s1,v1.19.12-k3s1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: ${{ matrix.k8s_version }}
      - name: Test on k3s
        run: |
          kubectl get nodes

      - name: Run chart-testing (install)
        run: ct install